demo1/demo1/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import url,include

urlpatterns = [
    path('admin/', admin.site.urls),
    url('demo2/',include('demo2.urls',namespace='demo2url'))

]

demo1/demo2/urls.py
from django.conf.urls import url
from . import views

app_name='demo2url'

urlpatterns = [
    url(r'^list/$', views.list,name='list'),
    url(r'^hero/(\d+)/$', views.hero,name='hero'),
    url(r'^index/$',views.index,name='index'),
    url(r'^deletebook/(\d+)/$',views.deletebook,name='deletebook'),
    url(r'^deletehero/(\d+)$',views.deletehero,name='deletehero'),
    url(r'^addhero/(\d+)/$',views.addhero,name='addhero'),
    url(r'^addbook/$',views.addbook,name='addbook'),
]

demo1/demo2/models.py
from django.db import models

# Create your models here.
class Bookinfo(models.Model):
    title=models.CharField(max_length=20)
    data=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

class Heroinfo(models.Model):
    name =models.CharField(max_length=20)
    age=models.IntegerField()
    skill=models.CharField(max_length=20,null=True)
    book=models.ForeignKey(Bookinfo,on_delete=models.CASCADE)

    def __str__(self):
        return self.name

demo1/demo2/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from django.template import loader
from .models import Bookinfo,Heroinfo
# Create your views here.

def index(request):
    # return HttpResponse('首页')
    # 获取模板--参数制定了模板位置为demo2文件夹下面的index.html
    temp=loader.get_template('demo2/index.html')
    # 渲染数据--参数是要发送给模板的数据此处用了{}表示不传数据
    result=temp.render({})
    # 返回
    return HttpResponse(result)

def list(request):

    # if request.method=='GET':
    # 获取模板--参数制定了模板位置为demo2文件夹下面的index.html
    temp = loader.get_template('demo2/list.html')
    # 渲染数据--参数是要发送给模板的数据此处用了{}表示不传数据
    books=Bookinfo.objects.all()    #此处获得bookinfo表中的所有数据 并且保存给books
    result = temp.render({'books':books})   #将数据渲染模板
    # 返回
    return HttpResponse(result)
    # elif request.method=='POST':
    #     book=request.POST['bookname']
    #     b1=Bookinfo()
    #     b1.title=book
    #     b1.save()
    #     return HttpResponseRedirect('/demo2/list/')

def hero(request,bookid):
    # 获取模板--参数制定了模板位置为demo2文件夹下面的index.html
    temp = loader.get_template('demo2/hero.html')
    # 渲染数据--参数是要发送给模板的数据此处用了{}表示不传数据
    book=Bookinfo.objects.get(id=bookid)  #这里从bookinfo表中查询一本书  根据bookid来查询
    result = temp.render({'book':book})
    # 返回
    return HttpResponse(result)

def deletebook(request,id):
    Bookinfo.objects.get(pk=id).delete()
    # return HttpResponse('成功')
    return HttpResponseRedirect('/demo2/list/')

def addbook(request):
    if request.method == 'GET':
        return render(request,'demo2/addbook.html')
    elif request.method=='POST':
        book=request.POST['bookname']
        b1=Bookinfo()
        b1.title=book
        b1.save()
        return HttpResponseRedirect('/demo2/list/')

def deletehero(request,id):
    # return HttpResponse('成功')
    hero=Heroinfo.objects.get(pk=id)

    a=hero.book.id
    hero.delete()
    return HttpResponseRedirect('/demo2/hero/%s/'%(a,))


def addhero(request,bookid):
    if request.method=='GET':
        return render(request,'demo2/addhero.html',{'bookid':bookid})
    elif request.method=='POST':
        obj=Bookinfo.objects.get(pk=bookid)
        h1=Heroinfo()
        h1.name=request.POST['username']
        h1.age=request.POST['age']
        h1.skill=request.POST['skill']
        h1.book=obj
        h1.save()
        return HttpResponseRedirect('/demo2/hero/%s/'%(bookid,))

demo1/templates/demo2/addbook.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加书</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>
<body>
    <div class="container">
        <h1>添加一本书</h1>
        <form action="{% url 'demo2url:addbook' %}" method="post">
        书名: <input type="text" name="bookname">
            <input type="submit" value="添加">
        </form>
    </div>











</body>
</html>

demo1/templates/demo2/addhero.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加角色</title>
</head>
<body>
    <h1>添加英雄</h1>

    <form action="{% url 'demo2url:addhero' bookid %}" method="post">

        姓名: <input type="text" name="username">
        <br>
        年龄: <input type="number" name="age" min="0">
        <br>
        技能: <input type="text" name="skill">
        <br>
        <input type="submit" value="添加">

    </form>




</body>
</html>

demo1/templates/demo2/hero.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>英雄</title>
     <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
    <div class="main">
        <h1>英雄</h1>

        {% if book %}

            <ul>
                {% for i in book.heroinfo_set.all %}
                <li>{{ i.name }} <a href="{% url 'demo2url:deletehero' i.id%}">删除</a></li>
                {% empty %}
                没有数据
                {% endfor %}
            </ul>
        {% else %}
            没有英雄
        {% endif %}

        <a href="{% url 'demo2url:addhero' book.id %}">添加英雄</a>
        <a href="/demo2/index/">主页</a>
        <a href="{% url 'demo2url:index' %}">返回主页</a>
        <a href="/demo2/list/">书籍列表</a>
        <a href="{% url 'demo2url:list' %}">返回书籍列表</a>
    </div>


</body>
</html>

demo1/templates/demo2/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>

   <div class="container">
        <h1>首页</h1>
        <a href="/demo2/list/">书籍列表</a>
        <a href="{% url 'demo2url:list' %}">去书籍列表</a>
       <br>

       <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
      </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img src="/static/img/silderbooks/hot1.jpg" alt="...">
          <div class="carousel-caption">
            向少年飞驰
          </div>
        </div>
        <div class="item">
          <img src="/static/img/silderbooks/hot2.jpg" alt="...">
          <div class="carousel-caption">
            点亮天赋
          </div>
        </div>
          <div class="item">
          <img src="/static/img/silderbooks/hot3.jpg" alt="...">
          <div class="carousel-caption">
            点亮天赋
          </div>
        </div>


      </div>

      <!-- Controls -->
      <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>

   </div>


   <script>


       $('.carousel').carousel({
          interval: 1500
        })


   </script>

</body>
</html>

demo1/templates/demo2/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>列表</title>
     <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
    <div class="main">
        <h1>列表</h1>

        {% if books %}
        <!--有书-->
            <ul>
                {% for i in books %}
                <li><a href="/demo2/hero/{{ i.id }}/">{{ i.title }}</a></li>
                <li><a href="{% url 'demo2url:hero' i.id %}">{{i.title}}</a> <a href="{% url 'demo2url:deletebook' i.id %}">删除</a></li>
                {% empty %}
                没有数据
                {% endfor %}
            </ul>
        {% else %}
            没有书
        {% endif %}

        <a href="{% url 'demo2url:addbook' %}">添加一本书</a>
        <a href="/demo2/index/">主页</a>
        <a href="{% url 'demo2url:index' %}">去主页</a>


    </div>

</body>
</html>